In [3]:
x = [1,2,3,4,4]
for value in x:
    print("hi")


hi
hi
hi
hi
hi


In [4]:
import numpy as np

# Creating a horizontal vector
vector = np.array([10, 20, 30, 40, 50])
print("Horizontal Vector:", vector)


Horizontal Vector: [10 20 30 40 50]


In [2]:
import numpy as np

# Creating matrices
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix2 = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# Performing basic operations
# Addition
addition = matrix1 + matrix2
print("Addition:\n", addition)

# Subtraction
subtraction = matrix1 - matrix2
print("Subtraction:\n", subtraction)

# Multiplication (element-wise)
multiplication = matrix1 * matrix2
print("Multiplication (element-wise):\n", multiplication)

# Matrix Multiplication
matrix_multiplication = np.dot(matrix1, matrix2)
print("Matrix Multiplication:\n", matrix_multiplication)

# Transpose
transpose = np.transpose(matrix1)
print("Transpose:\n", transpose)

# Inverse (only for non-singular matrices)
try:
    inverse = np.linalg.inv(matrix1)
    print("Inverse:\n", inverse)
except np.linalg.LinAlgError:
    print("Matrix1 is singular and cannot be inverted.")


Addition:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Subtraction:
 [[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]
Multiplication (element-wise):
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Matrix Multiplication:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Transpose:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Matrix1 is singular and cannot be inverted.
